// JFD RMS type-aware incident workflow
(function(){
  const groups=[
    {key:"fire",icon:"🔥",title:"Fire",desc:"Structure, outside, vehicle, alarm and other fire incidents.",test:/^FIRE\|?/},
    {key:"ems",icon:"🚑",title:"EMS / Medical",desc:"Illness, injury, cardiac and patient-care calls.",test:/^MEDICAL\|?/},
    {key:"mva",icon:"🚗",title:"MVA / Transportation",desc:"Motor vehicle collisions and transportation incidents.",test:/MOTOR_VEHICLE|TRANSPORTATION|COLLISION|CRASH/},
    {key:"rescue",icon:"🧯",title:"Rescue",desc:"Extrication, confined space, water, high-angle and collapse rescues.",test:/^RESCUE\|?/},
    {key:"hazmat",icon:"☣️",title:"Hazmat / Hazardous",desc:"Hazardous materials, releases, gas, electrical and overpressure.",test:/^HAZSIT\|?/},
    {key:"public",icon:"🛠️",title:"Public Service / Other",desc:"Citizen assists, alarms, weather and other service calls.",test:/^PUBSERV|^LAWENFORCE/},
    {key:"noemerg",icon:"🚫",title:"No Emergency / Cancelled",desc:"False alarms, cancelled calls and good-intent responses.",test:/^NOEMERG\|?/}
  ];
  const groupFor=v=>groups.find(g=>g.test.test(String(v||"").toUpperCase()))||groups[6];
  const fld=(id,label,val="",type="text",cls="",req=false)=>'<label class="text-sm font-semibold '+cls+'">'+esc(label)+(req?' *':'')+'<input id="'+id+'" type="'+type+'" value="'+esc(val??"")+'" '+(req?'required':'')+' class="w-full border rounded-lg p-2 mt-1 bg-white"></label>';
  const sel=(id,label,opts,val="",cls="",req=false)=>'<label class="text-sm font-semibold '+cls+'">'+esc(label)+(req?' *':'')+'<select id="'+id+'" '+(req?'required':'')+' class="w-full border rounded-lg p-2 mt-1 bg-white"><option value="">Select...</option>'+opts.map(o=>'<option value="'+esc(o.value??o)+'" '+(String(o.value??o)===String(val)?'selected':'')+'>'+esc(o.label??o)+'</option>').join('')+'</select></label>';
  const area=(id,label,val="",cls="")=>'<label class="text-sm font-semibold '+cls+'">'+esc(label)+'<textarea id="'+id+'" rows="4" class="w-full border rounded-lg p-2 mt-1 bg-white">'+esc(val??"")+'</textarea></label>';
  const card=(title,body,cls="")=>'<section class="rounded-2xl border bg-white shadow-sm p-4 sm:p-5 '+cls+'"><h3 class="text-lg font-black mb-3">'+title+'</h3><div class="grid md:grid-cols-2 gap-3">'+body+'</div></section>';
  function form(i,d,m,units){
    const primary=d?.primary_incident_type||d?.neris_incident_type||d?.incident_type||i?.type||"";
    let h=card('<span class="text-red-600">JASPER FIRE DEPARTMENT</span><div class="text-xs text-slate-500 font-semibold mt-1">INCIDENT REPORT</div>',
      fld("rDate","Incident Date",/^\d{4}-\d{2}-\d{2}/.test(String(i?.dispatch_time||""))?String(i.dispatch_time).slice(0,10):"","date")+fld("rCad","CAD / Incident Number",i?.cad||"","text","",true)+sel("rCall","Call Type",["EMS","Fire","Fire Alarm","Hazard","MVA","Public Service","Rescue","Special Duty","Custom"],d?.call_type||i?.type||"")+fld("rLocation","Location",i?.location||"","text","md:col-span-2",true)+fld("rLatitude","Latitude",i?.latitude??"","number")+fld("rLongitude","Longitude",i?.longitude??"","number")+sel("rShift","Shift",["A","B","C"],m?.shift||"")+jfdNerisSelect("rPrimaryIncidentType","Primary Incident Type",NERIS_INCIDENT_TYPES,primary,"md:col-span-2",true)+fld("rDispatchIncidentNumber","Dispatch Incident Number",i?.dispatch_incident_number||i?.cad||"")+fld("rCallArrival","Call Arrival",localDateTime(i?.call_arrival||i?.dispatch_time),"datetime-local")+fld("rCallAnswered","Call Answered",localDateTime(i?.call_answered||i?.dispatch_time),"datetime-local")+fld("rCallCreate","Call Create",localDateTime(i?.call_create||i?.dispatch_time),"datetime-local"));
    h+=reportResponseSection(units);
    h+=card("Property & Location Use",jfdNerisSelect("rLocationType","Location Type",NERIS_LOCATION_TYPES,d?.location_type||"")+jfdNerisSelect("rPrimaryUse","Primary Location Use",NERIS_LOCATION_USES,d?.primary_use||"","md:col-span-2")+jfdNerisSelect("rSecondaryUse","Secondary Location Use",NERIS_LOCATION_USES,d?.secondary_use||"","md:col-span-2")+sel("rLocationInUse","Location In Use",["Yes","No"],d?.location_in_use||"")+sel("rUsedAsIntended","Used as Intended",["Yes","No"],d?.used_as_intended||"")+sel("rPeoplePresent","People Present",["Yes","No"],d?.people_present||""));
    h+='<div id="jfdTypeFire" class="jfd-type-module">'+card("Fire Details",sel("rFireLoc","Fire Location",["Structure","Outside"],d?.fire_location||"")+sel("rCondition","Arrival Condition",["No Smoke/Fire Showing","Smoke Showing","Smoke and Fire Showing","Structure Involved","Fire Spread Beyond Structure","Fire Out Upon Arrival"],d?.arrival_condition||"")+sel("rDamageType","Damage Type",["No Damage","Minor","Moderate","Major"],d?.damage_type||"")+fld("rFloor","Floor of Origin",d?.floor_of_origin||"","number")+sel("rRoom","Room of Origin",["Assembly","Bathroom","Bedroom","Kitchen","Living Space","Hallway/Foyer","Garage","Basement","Attic","Office","Utility Room","Other","Unknown"],d?.room_of_origin||"")+sel("rCause","Fire Cause",["Operating Equipment","Electrical","Battery/Power Storage","Heat From Another Object","Explosives/Fireworks","Smoking Materials/Illicit Drugs","Open Flame","Cooking","Chemical","Act Of Nature","Incendiary","Other Heat Source","Unable to be Determined"],d?.cause||"")+sel("rWater","Water Supply",["Hydrant","Tank Water","Shuttle","Nurse from Other Apparatus","Draft from Static Source","Supply From Fire Boat","Foam / Water Additive"],d?.water_supply||"")+sel("rInvestigation","Investigation Required?",["Yes","No"],d?.investigation||""))+'</div>';
    h+='<div id="jfdTypeMedical" class="jfd-type-module">'+card("Medical / Patient Care",'<div class="md:col-span-2"><div id="jfdPatients"></div><button type="button" onclick="jfdAddPatient({})" class="mt-2 bg-blue-700 text-white px-3 py-2 rounded-lg font-bold text-sm">+ Add Patient</button></div>')+'</div>';
    h+='<div id="jfdTypeMva" class="jfd-type-module">'+card("MVA / Transportation",fld("rMvaRoadway","Roadway / Location Detail",d?.mva_roadway||"")+sel("rMvaExtrication","Extrication Required?",["Yes","No"],d?.mva_extrication||"")+fld("rVehicleCount","Vehicles Involved",d?.vehicle_count||"","number")+area("rMvaNotes","Collision / Transportation Notes",d?.mva_notes||"","md:col-span-2"))+'</div>';
    h+='<div id="jfdTypeRescue" class="jfd-type-module">'+card("Rescue / Extrication",sel("rRescueType","Rescue Type",["Extrication / Entrapped","Confined Space Rescue","High Angle Rescue","Low Angle Rescue","Steep Angle Rescue","Water Rescue","Building / Structure Collapse","Elevator / Escalator Rescue","Limited / No Access","Other"],d?.rescue_type||"")+sel("rRescueMode","Primary Rescue Mode",["Hand Tools","Hydraulic Tools","Rope","Water Rescue","Air Rescue","Ladder","Other"],d?.rescue_mode||"")+area("rRescueActions","Rescue Actions",d?.rescue_actions||"","md:col-span-2")+area("rRescueNotes","Rescue / Extrication Notes",d?.rescue_notes||"","md:col-span-2"))+'</div>';
    h+='<div id="jfdTypeHazmat" class="jfd-type-module">'+card("Hazmat / Hazardous Situation",sel("rHazDisposition","Hazardous Situation Disposition",["Contained","Released","Contained / Cleaned Up","No Release","Other"],d?.hazsit_disposition||"")+fld("rHazEvacuated","People Evacuated",d?.hazsit_evacuated||"","number")+fld("rChemicalName","Chemical Name(s)",d?.chemical_name||"")+fld("rChemicalClass","DOT Class",d?.chemical_dot_class||"")+sel("rChemicalRelease","Chemical Release Occurred?",["Yes","No","Unknown"],d?.chemical_release_occurred||"")+area("rHazNotes","Hazard / Mitigation Notes",d?.haz_notes||"","md:col-span-2"))+'</div>';
    h+='<div id="jfdTypePublic" class="jfd-type-module">'+card("Public Service / Other",area("rPublicService","Service / Response Details",d?.public_service||"","md:col-span-2"))+'</div>';
    h+='<div id="jfdTypeNoemerg" class="jfd-type-module">'+card("No Emergency / Cancelled",sel("rNoEmergReason","Disposition",["Cancelled","False Alarm","No Incident Found Upon Arrival","Good Intent","Location Error","Other"],d?.no_emerg_reason||"")+area("rNoEmergNotes","Notes",d?.no_emerg_notes||"","md:col-span-2"))+'</div>';
    h+=card("Actions & Tactics",'<div class="md:col-span-2"><div class="flex flex-wrap gap-5"><label class="flex items-center gap-2 text-sm font-semibold"><input id="rActionTaken" type="checkbox" onchange="jfdRenderActionControls()"> Action Taken</label><label class="flex items-center gap-2 text-sm font-semibold"><input id="rNoActionTaken" type="checkbox" onchange="jfdRenderActionControls()"> No Action Taken</label></div><div id="jfdActionControls" class="mt-3"></div></div>');
    h+='<div id="jfdTypeStructureExtras" class="jfd-type-module">'+card("Structure Fire Risk Reduction",sel("rSmokePresence","Smoke Alarm",["Present","Not Present","Not Applicable"])+sel("rFireAlarm","Fire Alarm",["Present","Not Present","Not Applicable"])+sel("rOtherAlarm","Other Alarm",["Present","Not Present","Not Applicable"])+sel("rSuppression","Fire Suppression",["Present","Not Present","Not Applicable"])+sel("rCookingSuppression","Cooking Fire Suppression",["Present","Not Present","Not Applicable"]))+'</div>';
    h+=repeatedSection("Exposures","exposures","Exposure",d?.exposures||[],x=>x)+repeatedSection("Casualties / Rescues","casualties","Casualty / Rescue",d?.casualties||[],x=>x)+repeatedSection("Hazards","hazards","Hazard",d?.hazards||[],x=>x)+repeatedSection("Vehicles","vehicles","Vehicle",d?.vehicles||[],x=>x);
    h+=card("Narrative & Completion",area("rNarrative","Narrative",d?.narrative||"","md:col-span-2")+area("rImpedimentNarrative","Impediment / Operational Notes",d?.impediment_narrative||"","md:col-span-2")+fld("rCompletedBy","Report Completed By",(d?.completed_by)||((profile?.first_name||"")+" "+(profile?.last_name||""))));
    h+='<div class="flex flex-wrap justify-between gap-2 pt-2 border-t"><button type="button" onclick="saveReportDraft(window.currentReportKind)" class="border px-4 py-2 rounded-lg font-bold">Save Draft</button><div class="flex gap-2"><button type="button" onclick="closeReportModal()" class="border px-4 py-2 rounded-lg font-bold">Cancel</button><button type="button" onclick="validateAndFinishReport(window.currentReportKind)" class="bg-amber-600 text-white px-5 py-2 rounded-lg font-bold">Validate & Finish</button></div></div>';
    setTimeout(()=>{jfdRenderIncidentTypes?.();jfdRenderActionControls?.();window.jfdRenderTypeModules?.();if(Array.isArray(d?.patients))jfdRenderPatients(d.patients);},0);return h;
  }
  window.jfdRenderTypeModules=function(){const g=groupFor($("rPrimaryIncidentType")?.value||"");document.querySelectorAll(".jfd-type-module").forEach(x=>x.classList.add("hiddenx"));(g.key==="fire"?["jfdTypeFire","jfdTypeStructureExtras"]:g.key==="ems"?["jfdTypeMedical"]:g.key==="mva"?["jfdTypeMva"]:g.key==="rescue"?["jfdTypeRescue"]:g.key==="hazmat"?["jfdTypeHazmat"]:g.key==="public"?["jfdTypePublic"]:["jfdTypeNoemerg"]).forEach(id=>$(id)?.classList.remove("hiddenx"));$("reportModalTitle").textContent=g.key==="ems"?"Patient Care Report":g.title+" Incident Report";};
  window.jfdOpenGeneralReport=async function(i,d,units){window.currentReportKind="general";$("reportChooser").classList.add("hiddenx");$("incidentReportForm").classList.remove("hiddenx");$("incidentReportForm").innerHTML=form(i,d,{shift:$("staffShift")?.value||""},units);bindReportForm("general");try{await refreshReportApparatusCrews(iDateForReport(i?.dispatch_time))}catch(e){}window.jfdRenderTypeModules();};
  window.jfdChooseExactIncidentType=function(){const v=$("jfdChooserNerisType")?.value;if(!v)return alert("Select a primary NERIS incident type first.");const m=$("reportModal"),id=Number(m?.dataset.incidentId||0),cad=m?.dataset.cad||"";if(!id)return startStandaloneReport("general");Promise.all([db.from("incidents").select("*").eq("cad",cad).maybeSingle(),db.from("incident_details").select("*").eq("incident_id",id).maybeSingle(),db.from("incident_units").select("*").eq("incident_id",id).order("incident_unit_id")]).then(async r=>{if(r[0].error||!r[0].data)return alert(r[0].error?.message||"Incident not found.");const d={...(r[1].data||{}),primary_incident_type:v};await jfdOpenGeneralReport(r[0].data,d,r[2].data||[]);$("rPrimaryIncidentType").value=v;window.jfdRenderTypeModules();});};
  window.jfdChooseGroup=function(key){const g=groups.find(x=>x.key===key)||groups[0];const hit=NERIS_INCIDENT_TYPES.find(x=>g.test.test(String(x.value||x)));if(hit){$("jfdChooserNerisType").value=hit.value;window.jfdChooseExactIncidentType();}else alert("Choose an exact NERIS incident type from the list.");};
  window.renderReportChooser=function(i,d,units){setReportIncidentContext(i,d);$("reportModalTitle").textContent="Create Incident Report";$("reportModalSub").textContent=(i?.location||"")+" · Select the primary incident type first";$("incidentReportForm").classList.add("hiddenx");$("reportChooser").classList.remove("hiddenx");$("reportChooser").innerHTML='<div class="max-w-5xl mx-auto"><h3 class="text-xl font-black mb-2">Start with the Primary Incident Type</h3><p class="text-sm text-slate-500 mb-5">JFD RMS will open only the report sections that apply to the selected NERIS type.</p><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">'+groups.map(g=>'<button type="button" onclick="jfdChooseGroup(\''+g.key+'\')" class="border-2 border-slate-200 hover:border-red-500 rounded-2xl p-5 text-left bg-white"><div class="text-2xl">'+g.icon+'</div><div class="font-black text-lg mt-2">'+g.title+'</div><div class="text-sm text-slate-500 mt-1">'+g.desc+'</div></button>').join('')+'</div><div class="mt-5 border rounded-xl p-4 bg-slate-50"><div class="font-bold mb-2">Or choose the exact NERIS primary type</div>'+jfdNerisSelect("jfdChooserNerisType","NERIS Primary Incident Type",NERIS_INCIDENT_TYPES,d?.primary_incident_type||"")+'<button type="button" onclick="jfdChooseExactIncidentType()" class="mt-3 bg-slate-950 text-white px-4 py-2 rounded-lg font-bold">Use Selected Type</button></div></div>';};
  window.newReport=function(){if(!canOps())return alert("You must be on duty.");const m=ensureReportModal();m.dataset.incidentId="";m.dataset.cad="";m.dataset.standalone="1";m.classList.remove("hiddenx");$("incidentReportForm").classList.add("hiddenx");$("reportChooser").classList.remove("hiddenx");window.renderReportChooser({},{},[]);};
})();